ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';

ALTER TABLE "ClassRoom" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
